# Generated by Django 5.0.1 on 2025-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('againpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
